### ISSUE TITLE
LICENSE file?

### ISSUE THREAD

**Issue by GregOwen** [rocicorp/fracdex#5]
Hello all,

We'd love to use this library in one of our services, but it doesn't have an explicit LICENSE file. I see that the JS implementation has a [LICENSE](https://github.com/rocicorp/fractional-indexing/blob/main/LICENSE); if this repo is meant to use the same license could you please make that explicit?

Thanks!

**Comment by arv** [comment]
Yes. It should have the same License.

**Comment by arv** [comment]
Fixed with ebc26eac9486ce231b707a162a2bef3d9143c8f2

**Comment by GregOwen** [comment]
Thanks!
